### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by Alexei303** [lucko/BungeeGuard#11]
I put the bungeeguard proxy on the bungeecord server and the bungeeguard backend on my backend servers and it doesn't work... people can still come in from another proxy, i am sure i made the settings in the right way, can you help me? And yes, I use paper

**Comment by ChineseMarc** [comment]
Are you using 1.8 or 1.7 cause playerhandshakeevent is added in 1.9.4 paper

**Comment by ChineseMarc** [comment]
Also
Compatibility
BungeeGuard is known to have compatibility issues with SkinsRestorer on the proxy side. This has been fixed in a SkinsRestorer update, please ensure you are using the latest version.

BungeeGuard is known to have compatibility issues with ProtocolSupport on the backend side. This has been fixed in a ProtocolSupport update, please ensure you are using the latest version.
