### ISSUE TITLE
New build bugs

### ISSUE THREAD

**Issue by DeveloperBoy** [lucko/BungeeGuard#22]
Hello,

I've installed the newest build [from 4 November] onto my servers, but now I always get this message:

`[BungeeGuard] Denied connection from UUID @ IP - A token was not included in their GameProfile properties.`
`Disconnecting com.mojang.authlib.GameProfile@188499b9[id=0c0d845b-531b-385b-819c-33b6f7d7d130,name=SBDeveloper,properties={},legacy=false]`

And at startup:
`[BungeeGuard] Using Bukkit's PlayerLoginEvent for connection filtering. Please consider upgrading to Paper (https://papermc.io/) to allow BungeeGuard to filter connections at the handshake stage (better!).`

Am I doing something wrong, or is there anything else wrong with the build?
The tokens in the files are the same, so that's not the problem.

I'm running the latest builds of BungeeGuard, Bungeecord and PaperSpigot 1.8.8.

Thanks in advance.

Kind regards,

Stijn

**Comment by DeveloperBoy** [comment]
Hello?

**Comment by VarChar42** [comment]
I have the same issue.

**Comment by lucko** [comment]
Sorry for the delay, I've just reverted the newer changes for now.

0f3edc2275482589e202778abea1122d3a0309dc

**Comment by MrMicky-FR** [comment]
> I'm running the latest builds of BungeeGuard, Bungeecord and PaperSpigot 1.8.8.

The PlayerHandshakeEvent was added in Paper in 1.9, so **when using Paper 1.8, BungeeGuard will don't do anything** (and the server is not protected) since the event don't exists in this version.

If the connection fail with the Spigot compatiblity it's most likely because BungeeGuard is not correctly configured on the proxy, and the Spigot compatibility just show the problem.

Also on servers with the PlayerHandshakeEvent there is absolutly no changes on the process with the Spigot compatibility (the Spigot listener is only use when the PlayerHandshakeEvent don't exists).

@lucko I think the Spigot compatibility can be added back because this is a configuration problem (BungeeGuard can't cancel any connection on 1.8 without the Spigot compatibility because the PlayerHandshakeEvent don't exists so it's never call).

If there is an other problem with the Spigot compatibility I'd be happy to correct them 😃

**Comment by stijnb1234** [comment]
Thanks for your reply. I will try to test the connection again on a Spigot 1.12.2 server with the Spigot compatibility build and check if I just configured it wrong or if it is indeed not working.

**Comment by MrMicky-FR** [comment]
With the Spigot compatibiliy it should work with Paper 1.8.8 (tested and it works for me).
Can you test with the Spigot compatibility on Paper > 1.9 and then on the same proxy, test on Spigot or 1.8.8 Paper to see if BungeeGuard is correctly setup on the proxy.

Also make sure that bungeecord is enabled in the Spigot config on Spigot / 1.8 Paper.
